### ISSUE TITLE
Using pybkgmodel with LST data (DL2 and DL3)

### ISSUE THREAD

**Issue by juanjq** [cta-observatory/pybkgmodel#26]
Hello, I write this issue, because after trying many things I don't manage to get it working with LST data. I'm running it using last version and the standard DL2 data produced by the automatic pipeline, in the cluster, also I'm running from a clean environment with the specific versions of everything as specified at `pyproject.toml`. My configuration is quite basic as well:
```
data:
    mask: '/fefs/aswg/data/real/DL2/20240615/v0.10/tailcut84/nsb_tuning_0.22/dl2*.h5'
    cuts: ''
mode: 'runwise_exclusion'
output:
    directory: '.'
    prefix: ''
    overwrite: True
run_matching:
    time_delta: '0.3 hour'
    pointing_delta: '2 deg'
binning:
    mode: 'rectangular'
    extension:
    x: 
        min: '-2 deg'
        max: '2 deg'
        nbins: 10
    y: 
        min: '-2 deg'
        max: '2 deg'
        nbins: 10
    energy:
        min: '80 GeV'
        max: '8 TeV'
        nbins: 6
exclusion_regions:
    - 'icrs; circle(7.53, 45.81, 0.2d)'
```
I have also tried with all 4 possible modes and none of them manage to work. Basically the error that is given is the following:
```
- |#                                                  | 0 Elapsed Time: 0:00:00
2025-04-14T12:55:01: Generating background maps
The file is corrupted or is missing the event tree. Empty arrays will be returned.
```
Then I tried as well with LST DL3 data, as I saw that this was implemented recently, and I'm still getting errors, reporting the file format is not compatible: 

```
RuntimeError: Unsupported file format for '/fefs/aswg/workspace/juan.jimenez/data/real/mono/S241125n/v0.10.18/GammaDiffuse/prod_dedicated_profile_1/DL3/gh_dyn90/dl3_LST-1.Run19803.fits'
```
I can try to provide more information if needed, maybe I did something wrong from the start, so I wanted to ask if someone else experienced those problems and if it happens for some reason.
